"use strict";

require("dotenv").config();
const env = process.env.NODE_ENV || "development";
const config = require(".././config/config")[env];

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const gcURL =
      "https://storage.googleapis.com/" + config.gc_bucket + "/images";

    const systemLanguageId = await queryInterface.rawSelect(
      "system_languages",
      { where: { key: "en" } },
      ["id"]
    );

    await queryInterface.bulkInsert("countries", [
      {
        country_name: "Afghanistan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Albania",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Algeria",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Angola",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Andorra",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Argentina",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Armenia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Australia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Austria",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Azerbaijan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Bahamas",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Bangladesh",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Belarus",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Belgium",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Belize",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Benin",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Bhutan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Bolivia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Bosnia and Herzegovina",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Botswana",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Brazil",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Brunei Darussalam",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Bulgaria",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Burkina Faso",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Burundi",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Cambodia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Cameroon",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Canada",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Central African Republic",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Chad",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Chile",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "China",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Colombia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Comoros",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Democratic Republic of the Congo",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Costa Rica",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Cote d'Ivoire",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Croatia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Cuba",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Cyprus",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Czech Republic",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Denmark",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Djibouti",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Dominican Republic",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Ecuador",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Egypt",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "El Salvador",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Equatorial Guinea",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Eritrea",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Estonia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Ethiopia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Falkland Islands (Malvinas)",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Fiji",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Finland",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "France",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "French Polynesia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Gabon",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Gambia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Georgia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Germany",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Ghana",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Greece",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Greenland",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Guatemala",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Guinea",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Guinea-Bissau",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Guyana",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Haiti",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Honduras",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Hungary",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Iceland",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "India",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Indonesia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Iran",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Iraq",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Ireland",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Israel",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Italy",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Jamaica",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Japan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Jordan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Kazakhstan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Kenya",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "North Korea",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "South Korea",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Kuwait",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Kyrgyzstan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Lao People's Democratic Republic",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Latvia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Lebanon",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Lesotho",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Liberia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Libya",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Lithuania",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Luxembourg",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Macedonia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Madagascar",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Malawi",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Malaysia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Mali",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Mauritania",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Mexico",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Moldova",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Mongolia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Serbia and Montenegro",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Morocco",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Mozambique",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Myanmar",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Namibia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Nepal",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Netherlands",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Netherlands Antilles",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "New Zealand",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Nicaragua",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Niger",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Nigeria",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Norway",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Oman",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Pakistan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Palestine",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Panama",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Papua New Guinea",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Paraguay",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Peru",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Philippines",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Poland",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Portugal",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Puerto Rico",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Qatar",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Romania",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Russian Federation",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Rwanda",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Saudi Arabia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Senegal",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Serbia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Sierra Leone",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Slovakia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Slovenia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Solomon Islands",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Somalia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "South Africa",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Soviet Union",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Spain",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Sri Lanka",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Sudan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Suriname",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Swaziland",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Sweden",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Switzerland",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Syrian Arab Republic",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Taiwan, Province of China",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Tajikistan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Tanzania",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Thailand",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Timor-Leste",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Togo",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Trinidad and Tobago",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Tunisia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Turkey",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Turkmenistan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Uganda",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Ukraine",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "United Arab Emirates",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "United Kingdom",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "United States",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Uruguay",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Uzbekistan",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Vanuatu",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Venezuela",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Vietnam",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Vatican City",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Yemen",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Zambia",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        country_name: "Zimbabwe",
        system_language_id: systemLanguageId,
        background_image: gcURL + "/default.jpg",
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("countries", null, {});
  },
};
