"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("stamps", [
      {
        stamp_title: "Wanderer",
        stamp_type: "Level",
        level_type_id: 1,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Inquirer",
        stamp_type: "Level",
        level_type_id: 2,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Discoverer",
        stamp_type: "Level",
        level_type_id: 3,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Problem Solver",
        stamp_type: "Level",
        level_type_id: 4,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Adventure Seeker",
        stamp_type: "Level",
        level_type_id: 5,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Ambitious Explorer",
        stamp_type: "Level",
        level_type_id: 6,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Taste Maker",
        stamp_type: "Level",
        level_type_id: 7,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Geographer",
        stamp_type: "Level",
        level_type_id: 8,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Experienced Adventurer",
        stamp_type: "Level",
        level_type_id: 9,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "World Traveler",
        stamp_type: "Level",
        level_type_id: 10,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },


      {
        stamp_title: "Sous Chef",
        stamp_type: "Learning",
        level_type_id: 1,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Culinary Explorer",
        stamp_type: "Learning",
        level_type_id: 2,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Citizen Scientist",
        stamp_type: "Learning",
        level_type_id: 3,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Master Chef",
        stamp_type: "Learning",
        level_type_id: 4,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Agent of Change",
        stamp_type: "Learning",
        level_type_id: 5,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "World Adventurer",
        stamp_type: "Learning",
        level_type_id: 6,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Global Genius",
        stamp_type: "Learning",
        level_type_id: 7,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Budding Geographer",
        stamp_type: "Learning",
        level_type_id: 8,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Mathlete",
        stamp_type: "Learning",
        level_type_id: 9,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Social Scientist",
        stamp_type: "Learning",
        level_type_id: 10,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Expert Scientist",
        stamp_type: "Learning",
        level_type_id: 11,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Key Investigator",
        stamp_type: "Learning",
        level_type_id: 12,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Master Gamer",
        stamp_type: "Learning",
        level_type_id: 13,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Team Player",
        stamp_type: "Learning",
        level_type_id: 14,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Heart of Gold",
        stamp_type: "Learning",
        level_type_id: 15,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        stamp_title: "Quick Learner",
        stamp_type: "Learning",
        level_type_id: 16,
        system_language_id: 1,
        status: true,
        created_by: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("stamps", null, {});
  },
};
